version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 20
    commands:
      - echo Entered the install phase...
      - npm install -g @angular/cli

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ng build --configuration production
    
artifacts:
  files:
    - 'dist/my-angular-project/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
  
