AWSTemplateFormatVersion: 2010-09-09
Description: AWS Core Network Template


#Metadata: 

#Parameters: 


Resources:
  ProductionVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: ProductionVPC
        - Key: Environment
          Value: Production
    


#Outputs: