AWSTemplateFormatVersion: 2010-09-09
Description: AWS Core Network Template for Production Environment


#Metadata: 

#Parameters: 


Resources:
  ProductionVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: ProductionVPC
        - Key: Environment
          Value: Production

  ProductionPublicSubnet1:  
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: ProductionPublicSubnet1
        - Key: Environment
          Value: Production
      VpcId: !Ref ProductionVPC

  ProductionPublicSubnet2:  
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: ProductionPublicSubnet2
        - Key: Environment
          Value: Production
      VpcId: !Ref ProductionVPC

  ProductionPrivateSubnet1:  
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: ProductionPrivateSubnet1
        - Key: Environment
          Value: Production
      VpcId: !Ref ProductionVPC

  ProductionPrivateSubnet2:  
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: ProductionPrivateSubnet2
        - Key: Environment
          Value: Production
      VpcId: !Ref ProductionVPC

  ProductionVPCIntGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name
          Value: ProductionIntGateway
        - Key: Environment
          Value: Production

  ProductionVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ProductionVPC
      InternetGatewayId: !Ref ProductionVPCIntGateway

  ProdPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProductionVPC
      Tags: 
        - Key: Name
          Value: ProdPublicRouteTable
        - Key: Environment
          Value: Production

  ProdPublicRoute:
    Type: AWS::EC2::Route
    Properties:
       RouteTableId:
         Ref: ProdPublicRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: ProductionVPCIntGateway

  ProdPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ProdPublicRouteTable
      SubnetId: !Ref ProductionPublicSubnet1

  ProdPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ProdPublicRouteTable
      SubnetId: !Ref ProductionPublicSubnet2


Outputs:
  ProductionVPCID:
    Description: ProductionVPC ID
    Value: !Ref ProductionVPC
    Export:
      Name: ProductionVPC-ID
